global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rpg-backend-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-core:8080']

  - job_name: 'rpg-backend-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-auth:8081']

  - job_name: 'rpg-backend-admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-admin:8082']

  - job_name: 'postgres'
    static_configs:
      - targets: ['rpg-postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['rpg-redis-exporter:9121']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['rpg-cadvisor:8080']
