services:
  sonarqube:
    image: sonarqube:community
    container_name: rpg-sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_FORCEAUTHENTICATION=false
      - SONAR_SECURITY_REALM=
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - rpg-network

volumes:
  sonarqube_data:
    name: rpg-sonarqube-data
  sonarqube_extensions:
    name: rpg-sonarqube-extensions
  sonarqube_logs:
    name: rpg-sonarqube-logs
  sonarqube_temp:
    name: rpg-sonarqube-temp

networks:
  rpg-network:
    external: true
    name: rpg-network
